version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: bannote_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bannote_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - mysql-data-dev:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network-dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
