version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: fingerprint_db_dev
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}  # SPRING_DATASOURCE_USERNAME
      MYSQL_PASSWORD: ${DB_PASSWORD}  # SPRING_DATASOURCE_PASSWORD
    volumes:
      - mysql-data-dev:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - app-network-dev
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5

  app:
    image: kyumin1227/fingerprint_backend_spring:dev
    container_name: fingerprint_backend_dev
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      TZ: Asia/Seoul
      LINE_ACCESS_TOKEN: ${LINE_ACCESS_TOKEN}
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network-dev

volumes:
  mysql-data-dev:

networks:
  app-network-dev:
