apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fingerprint-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: test
  sources:
    - repoURL: https://github.com/kyumin1227/Fingerprint_Backend.git
      targetRevision: main
      path: helm-app
      helm:
        releaseName: helm-app
        valueFiles:
          - $values/values-test.yaml
    - repoURL: https://github.com/kyumin1227/argocd_values.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
