apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: test
  namespace: argocd
spec:
  description: "Test AppProject"
  sourceRepos:
    - https://github.com/kyumin1227/Fingerprint_Backend.git
    - https://github.com/kyumin1227/argocd_values.git
  destinations:
    - namespace: test
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
