cors:
  allowed-origins: http://localhost:4200, http://localhost:8080, http://localhost:3000, chrome-extension://*

custom:
  line:
    access-token: ${LINE_ACCESS_TOKEN_DEV}

  aws:
    s3:
      image-bucket:
        name: dev-bucket
      region: ap-northeast-1
      credentials:
        access-key: dev-access-key
        secret-key: dev-secret-key