custom:
  aws:
    s3:
      image-bucket:
        name: ${AWS_S3_IMAGE_BUCKET_NAME}
      region: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}

  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}

  line:
    access-token: ${LINE_ACCESS_TOKEN}

  google:
    client-id: ${GOOGLE_CLIENT_ID}