name: Build test

permissions:
  contents: read
  packages: write

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: fingerprint_backend_spring
      DOCKERHUB_USERNAME: kyumin1227
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITHUB_USERNAME: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run MySQL container for tests
        run: |
          docker run -d \
            --name mysql-test \
            -e MYSQL_ROOT_PASSWORD=root \
            -e MYSQL_DATABASE=fingerprint_db_test \
            -e MYSQL_USER=test \
            -e MYSQL_PASSWORD=test \
            -p 3306:3306 \
            --health-cmd="mysqladmin ping --silent" \
            --health-interval=10s \
            --health-timeout=5s \
            --health-retries=5 \
            mysql:latest

      - name: Wait for MySQL to be healthy
        run: |
          for i in {1..10}; do
            status=$(docker inspect --format='{{.State.Health.Status}}' mysql-test)
            echo "MySQL container status: $status"
            if [ "$status" == "healthy" ]; then
              echo "MySQL is healthy!"
              break
            fi
            sleep 5
          done

      - name: Build with Gradle (workflow profile)
        run: ./gradlew test --scan

      - name: Cleanup MySQL container
        if: always()
        run: docker rm -f mysql-test
